### ISSUE TITLE
Support workspace GlobalWind

### ISSUE THREAD

**Issue by boatbomber** [boatbomber/WindShake#11]
It's still in beta as of writing this, but Roblox has introduced a new wind property that impacts grass and particles.
https://create.roblox.com/docs/environment/global-wind

It would be nice if WindShake had an option to automatically match that property.

**Comment by VSCPlays** [comment]
I’ll be submitting a pull request soon!

**Comment by boatbomber** [comment]
I appreciate the interest, @VSCPlays! Sorry that I beat you to it.

**Comment by ghost** [comment]
I was about to do it but my implementation is bad
